# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=['C:/Users/vadim/PycharmProjects/PyGame/PygameProject'],
    binaries=[],
    datas=[('data/imgs/selected_ak.png', 'data/imgs'),
     ('data/imgs/ak.png', 'data/imgs'),
     ('data/imgs/awp.png', 'data/imgs'),
     ('data/imgs/bullet.png', 'data/imgs'),
     ('data/imgs/empty.png', 'data/imgs'),
     ('data/imgs/exit.png', 'data/imgs'),
     ('data/imgs/glass.png', 'data/imgs'),
     ('data/imgs/guns.png', 'data/imgs'),
     ('data/imgs/mark.png', 'data/imgs'),
     ('data/imgs/operative.png', 'data/imgs'),
     ('data/imgs/pistol.png', 'data/imgs'),
     ('data/imgs/selected_ak.png', 'data/imgs'),
     ('data/imgs/selected_awp.png', 'data/imgs'),
     ('data/imgs/selected_empty.png', 'data/imgs'),
     ('data/imgs/selected_exit.png', 'data/imgs'),
     ('data/imgs/selected_pistol.png', 'data/imgs'),
     ('data/imgs/selected_start.png', 'data/imgs'),
     ('data/imgs/simple_tile.png', 'data/imgs'),
     ('data/imgs/start.png', 'data/imgs'),
     ('data/imgs/tileUnderAttack.png', 'data/imgs'),
     ('data/imgs/wall.png', 'data/imgs'),
     ('data/imgs/zombie_wild.png', 'data/imgs'),
     ("data/ConfigurationsFiles/Level1/Characters", "data/ConfigurationsFiles/Level1"),
     ("data/ConfigurationsFiles/Level1/Items", "data/ConfigurationsFiles/Level1"),
     ("data/ConfigurationsFiles/Level1/Map", "data/ConfigurationsFiles/Level1")
     ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    )
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='OVSZ',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
